repos:
- repo: local
  hooks:
  - id: ruff
    name: ruff
    entry: uv run ruff check --fix
    language: python
    types_or: [ python, pyi ]
    require_serial: true
    stages: [ pre-commit ]
  - id: ruff-format
    name: ruff-format
    entry: uv run ruff format --force-exclude
    language: system
    types_or: [ python, pyi ]
    require_serial: true
    stages: [ pre-commit ]
  - id: mypy
    name: mypy
    entry: uv run mypy
    types_or: [ python, pyi ]
    pass_filenames: false
    language: python
    require_serial: true
    stages: [ pre-commit ]

