repos:
- repo: local
  hooks:
  - id: ruff-format
    name: ruff-format
    entry: uv run ruff format --force-exclude
    pass_filenames: true
    language: system
    types_or: [ python, pyi ]
    require_serial: true
    stages: [ pre-commit ]
  - id: ruff-check
    name: ruff-check
    entry: uv run ruff check --fix
    language: system
    types_or: [ python ]
    pass_filenames: true
    require_serial: false
    stages: [ pre-commit ]
  - id: mypy
    name: mypy
    entry: uv run mypy
    types_or: [ python, pyi ]
    pass_filenames: false
    language: system
    require_serial: true
    stages: [ pre-commit ]

